
package soapclient;

import java.util.ArrayList;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebService(name = "GetCompositeInfo",
            targetNamespace = "http://xmlns.oracle.com/GetCompositesInfo/GetCompositesInfo/GetCompositeInfo")
@XmlSeeAlso( { ObjectFactory.class })
public interface GetCompositeInfo {


    /**
     *
     * @param input
     * @return
     *     returns soapclient.ProcessResponse.Composite
     */
    @WebMethod(action = "process")
    @WebResult(name = "Composite",
               targetNamespace = "http://xmlns.oracle.com/GetCompositesInfo/GetCompositesInfo/GetCompositeInfo")
    @RequestWrapper(localName = "process",
                    targetNamespace = "http://xmlns.oracle.com/GetCompositesInfo/GetCompositesInfo/GetCompositeInfo",
                    className = "soapclient.Process")
    @ResponseWrapper(localName = "processResponse",
                     targetNamespace = "http://xmlns.oracle.com/GetCompositesInfo/GetCompositesInfo/GetCompositeInfo",
                     className = "soapclient.ProcessResponse")
    public ArrayList<soapclient.ProcessResponse.Composite> process(@WebParam(name =
                                                                  "input",
                                                                  targetNamespace =
                                                                  "http://xmlns.oracle.com/GetCompositesInfo/GetCompositesInfo/GetCompositeInfo")
        String input);

}
