
package soapclient;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "getcompositeinfo_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/GetCompositesInfo/GetCompositesInfo/GetCompositeInfo",
                  wsdlLocation =
                  "http://192.168.56.101:8001/soa-infra/services/tst/GetCompositeInfo/getcompositeinfo_client_ep?wsdl")
public class GetcompositeinfoClientEp extends Service {

    private final static URL GETCOMPOSITEINFOCLIENTEP_WSDL_LOCATION;
    private final static Logger logger =
        Logger.getLogger(soapclient.GetcompositeinfoClientEp.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl =
                    soapclient.GetcompositeinfoClientEp.class.getResource(".");
            url =
new URL(baseUrl, "http://192.168.56.101:8001/soa-infra/services/tst/GetCompositeInfo/getcompositeinfo_client_ep?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.56.101:8001/soa-infra/services/tst/GetCompositeInfo/getcompositeinfo_client_ep?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        GETCOMPOSITEINFOCLIENTEP_WSDL_LOCATION = url;
    }

    public GetcompositeinfoClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetcompositeinfoClientEp() {
        super(GETCOMPOSITEINFOCLIENTEP_WSDL_LOCATION,
              new QName("http://xmlns.oracle.com/GetCompositesInfo/GetCompositesInfo/GetCompositeInfo",
                        "getcompositeinfo_client_ep"));
    }

    /**
     *
     * @return
     *     returns GetCompositeInfo
     */
    @WebEndpoint(name = "GetCompositeInfo_pt")
    public GetCompositeInfo getGetCompositeInfoPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/GetCompositesInfo/GetCompositesInfo/GetCompositeInfo",
                                       "GetCompositeInfo_pt"),
                             GetCompositeInfo.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCompositeInfo
     */
    @WebEndpoint(name = "GetCompositeInfo_pt")
    public GetCompositeInfo getGetCompositeInfoPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/GetCompositesInfo/GetCompositesInfo/GetCompositeInfo",
                                       "GetCompositeInfo_pt"),
                             GetCompositeInfo.class, features);
    }

}
