Rem
Rem $Header: entsec_ldap/java/src/oracle/security/audit/rcu/scripts/iau11116.sql /st_entsec_11.1.1.9.0/4 2014/07/09 01:40:03 rkoul Exp $
Rem
Rem iau11116.sql
Rem
Rem Copyright (c) 2011, 2014, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      iau11116.sql - <one-line expansion of the name>
Rem
Rem    DESCRIPTION
Rem      <short description of component this file declares/defines>
Rem
Rem    NOTES
Rem      auditGenericTabs, SOA, XMLPSERER sqls are directly called 
Rem                        from this script
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    rkoul       07/08/14 - ps3/ps4 to ps7 upgrade: add missing ID_SEQ syn
Rem    rkoul       04/10/14 - alter ID_SEQ
Rem    rkoul       03/18/14 - IAU_ID index for ps7 upgrade
Rem    palrao      07/10/13 - Schema changes for PS7 upgrade
Rem    rkoul       12/20/12 - add user tenantid for ps6 upgrade
Rem    miqi        08/16/12 - fix bug 14504888
Rem    skalyana    10/16/11 - Additional changes for OAM
Rem    skalyana    10/09/11 - Fix for bug # 13042179
Rem    skalyana    07/22/11 - Created
Rem

-- &&1 - Audit Admin Role
-- &&2 - Audit Append Role
-- &&3 - Audit Viewer Role

ALTER SESSION SET CURRENT_SCHEMA=&&1;

ALTER TABLE OAAM
ADD IAU_CustomJobType VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_CustomJobTypeId NUMBER;
ALTER TABLE OAAM
ADD IAU_PatternDetails VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_PatternIds VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_PatternStatus VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_PatternId NUMBER;
ALTER TABLE OAAM
ADD IAU_PatternParam VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_PatternParamIds VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_TransactionDef VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_TransactionDefIds VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_TransactionDefStatus INTEGER;
ALTER TABLE OAAM
ADD IAU_TransactionEntityDefMap VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_TransactionEntityDefMapIds VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_TransactionDefId NUMBER;
ALTER TABLE OAAM
ADD IAU_DataElementDefArray VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_DataElementDefIds VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_TransactionDataMapping VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_TransactionDataMappingIds VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_TransactionEntityMapId NUMBER;
ALTER TABLE OAAM
ADD IAU_SnapshotData VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_SnapshotDiffTree VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_IsDeleteSnapshotItems NUMBER;
ALTER TABLE OAAM
ADD IAU_SnapshotIds VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_ImpExpPropertiesArgs VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_DynamicAction VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_DynamicActionIds VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_DynamicActionInstance VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_DynamicActionInstanceIds VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_DynamicActionInstStatus INTEGER;
ALTER TABLE OAAM
ADD IAU_PolicySet VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_PolicySetId NUMBER;
ALTER TABLE OAAM
ADD IAU_ScoreActions VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_ActionOverrides VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_ScoreActionIds VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_ActionOverrideBlockIds VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_PropertyName VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_PropertyValue VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_PropertyNames VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_EntityDef VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_EntityDefIds VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_EntityDefStatus INTEGER;
ALTER TABLE OAAM
ADD IAU_EntityDefId NUMBER;
ALTER TABLE OAAM
ADD IAU_IdSchemeElemDefIds VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_KeyGenScheme INTEGER;
ALTER TABLE OAAM
ADD IAU_DisplayElemDefIds VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_EntityDefsMap VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_RecentLoginsSearchQuery VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_RequestId VARCHAR(4000);
ALTER TABLE OAAM
ADD IAU_TrxLogId NUMBER;
ALTER TABLE OAAM
ADD IAU_RuntimeType INTEGER;
ALTER TABLE OAAM
ADD IAU_PolicySetLogId NUMBER;
ALTER TABLE OAAM
ADD IAU_EntityDefsMapIds VARCHAR(4000);

ALTER TABLE IAU_BASE
ADD IAU_AuditUser VARCHAR(255);
ALTER TABLE IAU_BASE
ADD IAU_TenantId VARCHAR(255);
ALTER TABLE IAU_BASE
ADD IAU_UserTenantId VARCHAR(255);
ALTER TABLE IAU_BASE
ADD IAU_ServerName VARCHAR(255);

-- create synonyms & base tables for dynamic metadata model
@@auditGenericTabs.sql &&1 &&2 &&3

CREATE or replace SYNONYM &&2..ID_SEQ FOR &&1..ID_SEQ;

@@SOA-B2B.sql &&1 &&2 &&3
@@SOA-HCFP.sql &&1 &&2 &&3
@@XMLPSERVER.sql &&1 &&2 &&3

ALTER TABLE OAM
ADD IAU_PolicyObjectID VARCHAR(255);
ALTER TABLE OAM
ADD IAU_ReadOnly VARCHAR(255);
ALTER TABLE OAM
ADD IAU_PolicyAdminContext CLOB;
ALTER TABLE OAM
ADD IAU_PolicyType VARCHAR(255);
ALTER TABLE OAM
ADD IAU_ProtectionLevel VARCHAR(255);
ALTER TABLE OAM
ADD IAU_ServiceURI VARCHAR(1024);
ALTER TABLE OAM
ADD IAU_ServiceIdentifier VARCHAR(255);
ALTER TABLE OAM
ADD IAU_ServiceOperation VARCHAR(255);
ALTER TABLE OAM
ADD IAU_AdminRoleName VARCHAR(255);
ALTER TABLE OAM
ADD IAU_ClientIPAddress VARCHAR(255);
ALTER TABLE OAM
ADD IAU_SessionCreationTime VARCHAR(255);
ALTER TABLE OAM
ADD IAU_SessionExpirationTime VARCHAR(255);
ALTER TABLE OAM
ADD IAU_SessionLastUpdateTime VARCHAR(255);
ALTER TABLE OAM
ADD IAU_SessionLastAccessTime VARCHAR(255);
ALTER TABLE OAM
ADD IAU_IdentityDomain VARCHAR(255);
ALTER TABLE OAM
ADD IAU_GenericAttribute1 VARCHAR(255);
ALTER TABLE OAM
ADD IAU_GenericAttribute2 VARCHAR(255);
ALTER TABLE OAM
ADD IAU_GenericAttribute3 VARCHAR(255);
ALTER TABLE OAM
ADD IAU_GenericAttribute4 VARCHAR(255);
ALTER TABLE OAM
ADD IAU_GenericAttribute5 VARCHAR(255);
ALTER TABLE OAM
ADD IAU_ResourceOperations VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_ApplicationDomainName VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_AuthenticationSchemeID VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_AgentID VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_SSOSessionID VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_AuthorizationScheme VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_ResourceID VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_AuthorizationPolicyID VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_UserID VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_PolicyName VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_SchemeName VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_ResourceHostName VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_OldAttributes VARCHAR(4000);
ALTER TABLE OAM
MODIFY IAU_NewAttributes VARCHAR(4000);
ALTER TABLE OAM
MODIFY IAU_ResponseType VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_AgentType VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_ConstraintType VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_InstanceName VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_DataSourceName VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_DataSourceType VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_HostIdentifierName VARCHAR(255);
ALTER TABLE OAM
MODIFY IAU_ResourceURI VARCHAR(1024);
ALTER TABLE OAM
MODIFY IAU_ResourceTemplateName VARCHAR(255);


ALTER SEQUENCE  ID_SEQ CACHE 100 INCREMENT BY 120;


-- indexes
CREATE INDEX AdminServer_Event_Index ON AdminServer(IAU_ID);
CREATE INDEX DIP_Event_Index ON DIP(IAU_ID);
CREATE INDEX JPS_Event_Index ON JPS(IAU_ID);
CREATE INDEX OAM_Event_Index ON OAM(IAU_ID);
CREATE INDEX OAAM_Event_Index ON OAAM(IAU_ID);
CREATE INDEX OHSComponent_Event_Index ON OHSComponent(IAU_ID);
CREATE INDEX OIDComponent_Event_Index ON OIDComponent(IAU_ID);
CREATE INDEX OIF_Event_Index ON OIF(IAU_ID);
CREATE INDEX OVDComponent_Event_Index ON OVDComponent(IAU_ID);
CREATE INDEX OWSM_AGENT_Event_Index ON OWSM_AGENT(IAU_ID);
CREATE INDEX OWSM_PM_EJB_Event_Index ON OWSM_PM_EJB(IAU_ID);
CREATE INDEX ReportsServer_Event_Index ON ReportsServerComponent(IAU_ID);
CREATE INDEX STS_Event_Index ON STS(IAU_ID);
CREATE INDEX WebCacheComponent_Event_Index ON WebCacheComponent(IAU_ID);
CREATE INDEX WebServices_Event_Index ON WebServices(IAU_ID);
CREATE INDEX WS_Policy_Event_Index ON WS_PolicyAttachment(IAU_ID);

-- common and custom indexes get created via call to auditGenericTabs.sql
CREATE INDEX EVENT_INDEX ON IAU_BASE(IAU_ID);

