Rem
Rem $Header: entsec_ldap/java/src/oracle/security/audit/rcu/scripts/iau11117.sql /st_entsec_11.1.1.9.0/6 2015/02/13 11:13:46 rkoul Exp $
Rem
Rem iau11117.sql
Rem
Rem Copyright (c) 2012, 2015, Oracle and/or its affiliates. 
Rem All rights reserved.
Rem
Rem    NAME
Rem      iau11117.sql - <one-line expansion of the name>
Rem
Rem    DESCRIPTION
Rem      <short description of component this file declares/defines>
Rem
Rem    NOTES
Rem      <other useful comments, qualifications, etc.>
Rem
Rem    MODIFIED   (MM/DD/YY)
Rem    rkoul       02/10/15 - add missing indexes/privs etc for ps5-ps7 upgrade
Rem    rkoul       04/10/14 - alter ID_SEQ
Rem    rkoul       03/18/14 - IAU_ID index for ps7 upgrade
Rem    palrao      07/10/13 - Schema changes for PS7 upgrade
Rem    skalyana    06/20/13 - Backport skalyana_bug-16405561 from
Rem                           st_entsec_12.1.2.0.0
Rem    rkoul       03/08/13 - fix typo in SCHEMA_VERSION
Rem    skalyana    03/11/13 - Bug # 16405561
Rem    rkoul       12/20/12 - add missing synonyms for tables
Rem    rkoul       12/20/12 - add user tenantid for ps6 upgrade
Rem    miqi        07/19/12 - Created
Rem

ALTER SESSION SET CURRENT_SCHEMA=&&1;

ALTER TABLE IAU_BASE
ADD IAU_AuditUser VARCHAR(255);
ALTER TABLE IAU_BASE
ADD IAU_TenantId VARCHAR(255);
ALTER TABLE IAU_BASE
ADD IAU_UserTenantId VARCHAR(255);
ALTER TABLE IAU_BASE
ADD IAU_ServerName VARCHAR(255);

ALTER TABLE IAU_COMMON
ADD IAU_AuditUser VARCHAR(255);
ALTER TABLE IAU_COMMON
ADD IAU_TenantId VARCHAR(255);
ALTER TABLE IAU_COMMON
ADD IAU_UserTenantId VARCHAR(255);
ALTER TABLE IAU_COMMON
ADD IAU_ServerName VARCHAR(255);

CREATE TABLE IAU_CUSTOM_01 (
      IAU_ID            NUMBER ,
      IAU_BOOLEAN_001   NUMBER,
      IAU_BOOLEAN_002   NUMBER,
      IAU_BOOLEAN_003   NUMBER,
      IAU_BOOLEAN_004   NUMBER,
      IAU_BOOLEAN_005   NUMBER,
      IAU_BOOLEAN_006   NUMBER,
      IAU_BOOLEAN_007   NUMBER,
      IAU_BOOLEAN_008   NUMBER,
      IAU_BOOLEAN_009   NUMBER,
      IAU_BOOLEAN_010   NUMBER,
      IAU_BOOLEAN_011   NUMBER,
      IAU_BOOLEAN_012   NUMBER,
      IAU_BOOLEAN_013   NUMBER,
      IAU_BOOLEAN_014   NUMBER,
      IAU_BOOLEAN_015   NUMBER,
      IAU_BOOLEAN_016   NUMBER,
      IAU_BOOLEAN_017   NUMBER,
      IAU_BOOLEAN_018   NUMBER,
      IAU_BOOLEAN_019   NUMBER,
      IAU_BOOLEAN_020   NUMBER,
      IAU_BOOLEAN_021   NUMBER,
      IAU_BOOLEAN_022   NUMBER,
      IAU_BOOLEAN_023   NUMBER,
      IAU_BOOLEAN_024   NUMBER,
      IAU_BOOLEAN_025   NUMBER,
      IAU_BOOLEAN_026   NUMBER,
      IAU_BOOLEAN_027   NUMBER,
      IAU_BOOLEAN_028   NUMBER,
      IAU_BOOLEAN_029   NUMBER,
      IAU_BOOLEAN_030   NUMBER,
      IAU_BOOLEAN_031   NUMBER,
      IAU_BOOLEAN_032   NUMBER,
      IAU_BOOLEAN_033   NUMBER,
      IAU_BOOLEAN_034   NUMBER,
      IAU_BOOLEAN_035   NUMBER,
      IAU_BOOLEAN_036   NUMBER,
      IAU_BOOLEAN_037   NUMBER,
      IAU_BOOLEAN_038   NUMBER,
      IAU_BOOLEAN_039   NUMBER,
      IAU_BOOLEAN_040   NUMBER,
      IAU_BOOLEAN_041   NUMBER,
      IAU_BOOLEAN_042   NUMBER,
      IAU_BOOLEAN_043   NUMBER,
      IAU_BOOLEAN_044   NUMBER,
      IAU_BOOLEAN_045   NUMBER,
      IAU_BOOLEAN_046   NUMBER,
      IAU_BOOLEAN_047   NUMBER,
      IAU_BOOLEAN_048   NUMBER,
      IAU_BOOLEAN_049   NUMBER,
      IAU_BOOLEAN_050   NUMBER,
      IAU_INT_001   NUMBER,
      IAU_INT_002   NUMBER,
      IAU_INT_003   NUMBER,
      IAU_INT_004   NUMBER,
      IAU_INT_005   NUMBER,
      IAU_INT_006   NUMBER,
      IAU_INT_007   NUMBER,
      IAU_INT_008   NUMBER,
      IAU_INT_009   NUMBER,
      IAU_INT_010   NUMBER,
      IAU_INT_011   NUMBER,
      IAU_INT_012   NUMBER,
      IAU_INT_013   NUMBER,
      IAU_INT_014   NUMBER,
      IAU_INT_015   NUMBER,
      IAU_INT_016   NUMBER,
      IAU_INT_017   NUMBER,
      IAU_INT_018   NUMBER,
      IAU_INT_019   NUMBER,
      IAU_INT_020   NUMBER,
      IAU_INT_021   NUMBER,
      IAU_INT_022   NUMBER,
      IAU_INT_023   NUMBER,
      IAU_INT_024   NUMBER,
      IAU_INT_025   NUMBER,
      IAU_INT_026   NUMBER,
      IAU_INT_027   NUMBER,
      IAU_INT_028   NUMBER,
      IAU_INT_029   NUMBER,
      IAU_INT_030   NUMBER,
      IAU_INT_031   NUMBER,
      IAU_INT_032   NUMBER,
      IAU_INT_033   NUMBER,
      IAU_INT_034   NUMBER,
      IAU_INT_035   NUMBER,
      IAU_INT_036   NUMBER,
      IAU_INT_037   NUMBER,
      IAU_INT_038   NUMBER,
      IAU_INT_039   NUMBER,
      IAU_INT_040   NUMBER,
      IAU_INT_041   NUMBER,
      IAU_INT_042   NUMBER,
      IAU_INT_043   NUMBER,
      IAU_INT_044   NUMBER,
      IAU_INT_045   NUMBER,
      IAU_INT_046   NUMBER,
      IAU_INT_047   NUMBER,
      IAU_INT_048   NUMBER,
      IAU_INT_049   NUMBER,
      IAU_INT_050   NUMBER,
      IAU_LONG_001   NUMBER,
      IAU_LONG_002   NUMBER,
      IAU_LONG_003   NUMBER,
      IAU_LONG_004   NUMBER,
      IAU_LONG_005   NUMBER,
      IAU_LONG_006   NUMBER,
      IAU_LONG_007   NUMBER,
      IAU_LONG_008   NUMBER,
      IAU_LONG_009   NUMBER,
      IAU_LONG_010   NUMBER,
      IAU_LONG_011   NUMBER,
      IAU_LONG_012   NUMBER,
      IAU_LONG_013   NUMBER,
      IAU_LONG_014   NUMBER,
      IAU_LONG_015   NUMBER,
      IAU_LONG_016   NUMBER,
      IAU_LONG_017   NUMBER,
      IAU_LONG_018   NUMBER,
      IAU_LONG_019   NUMBER,
      IAU_LONG_020   NUMBER,
      IAU_LONG_021   NUMBER,
      IAU_LONG_022   NUMBER,
      IAU_LONG_023   NUMBER,
      IAU_LONG_024   NUMBER,
      IAU_LONG_025   NUMBER,
      IAU_LONG_026   NUMBER,
      IAU_LONG_027   NUMBER,
      IAU_LONG_028   NUMBER,
      IAU_LONG_029   NUMBER,
      IAU_LONG_030   NUMBER,
      IAU_LONG_031   NUMBER,
      IAU_LONG_032   NUMBER,
      IAU_LONG_033   NUMBER,
      IAU_LONG_034   NUMBER,
      IAU_LONG_035   NUMBER,
      IAU_LONG_036   NUMBER,
      IAU_LONG_037   NUMBER,
      IAU_LONG_038   NUMBER,
      IAU_LONG_039   NUMBER,
      IAU_LONG_040   NUMBER,
      IAU_LONG_041   NUMBER,
      IAU_LONG_042   NUMBER,
      IAU_LONG_043   NUMBER,
      IAU_LONG_044   NUMBER,
      IAU_LONG_045   NUMBER,
      IAU_LONG_046   NUMBER,
      IAU_LONG_047   NUMBER,
      IAU_LONG_048   NUMBER,
      IAU_LONG_049   NUMBER,
      IAU_LONG_050   NUMBER,
      IAU_FLOAT_001   NUMBER,
      IAU_FLOAT_002   NUMBER,
      IAU_FLOAT_003   NUMBER,
      IAU_FLOAT_004   NUMBER,
      IAU_FLOAT_005   NUMBER,
      IAU_FLOAT_006   NUMBER,
      IAU_FLOAT_007   NUMBER,
      IAU_FLOAT_008   NUMBER,
      IAU_FLOAT_009   NUMBER,
      IAU_FLOAT_010   NUMBER,
      IAU_FLOAT_011   NUMBER,
      IAU_FLOAT_012   NUMBER,
      IAU_FLOAT_013   NUMBER,
      IAU_FLOAT_014   NUMBER,
      IAU_FLOAT_015   NUMBER,
      IAU_FLOAT_016   NUMBER,
      IAU_FLOAT_017   NUMBER,
      IAU_FLOAT_018   NUMBER,
      IAU_FLOAT_019   NUMBER,
      IAU_FLOAT_020   NUMBER,
      IAU_FLOAT_021   NUMBER,
      IAU_FLOAT_022   NUMBER,
      IAU_FLOAT_023   NUMBER,
      IAU_FLOAT_024   NUMBER,
      IAU_FLOAT_025   NUMBER,
      IAU_FLOAT_026   NUMBER,
      IAU_FLOAT_027   NUMBER,
      IAU_FLOAT_028   NUMBER,
      IAU_FLOAT_029   NUMBER,
      IAU_FLOAT_030   NUMBER,
      IAU_FLOAT_031   NUMBER,
      IAU_FLOAT_032   NUMBER,
      IAU_FLOAT_033   NUMBER,
      IAU_FLOAT_034   NUMBER,
      IAU_FLOAT_035   NUMBER,
      IAU_FLOAT_036   NUMBER,
      IAU_FLOAT_037   NUMBER,
      IAU_FLOAT_038   NUMBER,
      IAU_FLOAT_039   NUMBER,
      IAU_FLOAT_040   NUMBER,
      IAU_FLOAT_041   NUMBER,
      IAU_FLOAT_042   NUMBER,
      IAU_FLOAT_043   NUMBER,
      IAU_FLOAT_044   NUMBER,
      IAU_FLOAT_045   NUMBER,
      IAU_FLOAT_046   NUMBER,
      IAU_FLOAT_047   NUMBER,
      IAU_FLOAT_048   NUMBER,
      IAU_FLOAT_049   NUMBER,
      IAU_FLOAT_050   NUMBER,
      IAU_DOUBLE_001   NUMBER,
      IAU_DOUBLE_002   NUMBER,
      IAU_DOUBLE_003   NUMBER,
      IAU_DOUBLE_004   NUMBER,
      IAU_DOUBLE_005   NUMBER,
      IAU_DOUBLE_006   NUMBER,
      IAU_DOUBLE_007   NUMBER,
      IAU_DOUBLE_008   NUMBER,
      IAU_DOUBLE_009   NUMBER,
      IAU_DOUBLE_010   NUMBER,
      IAU_DOUBLE_011   NUMBER,
      IAU_DOUBLE_012   NUMBER,
      IAU_DOUBLE_013   NUMBER,
      IAU_DOUBLE_014   NUMBER,
      IAU_DOUBLE_015   NUMBER,
      IAU_DOUBLE_016   NUMBER,
      IAU_DOUBLE_017   NUMBER,
      IAU_DOUBLE_018   NUMBER,
      IAU_DOUBLE_019   NUMBER,
      IAU_DOUBLE_020   NUMBER,
      IAU_DOUBLE_021   NUMBER,
      IAU_DOUBLE_022   NUMBER,
      IAU_DOUBLE_023   NUMBER,
      IAU_DOUBLE_024   NUMBER,
      IAU_DOUBLE_025   NUMBER,
      IAU_DOUBLE_026   NUMBER,
      IAU_DOUBLE_027   NUMBER,
      IAU_DOUBLE_028   NUMBER,
      IAU_DOUBLE_029   NUMBER,
      IAU_DOUBLE_030   NUMBER,
      IAU_DOUBLE_031   NUMBER,
      IAU_DOUBLE_032   NUMBER,
      IAU_DOUBLE_033   NUMBER,
      IAU_DOUBLE_034   NUMBER,
      IAU_DOUBLE_035   NUMBER,
      IAU_DOUBLE_036   NUMBER,
      IAU_DOUBLE_037   NUMBER,
      IAU_DOUBLE_038   NUMBER,
      IAU_DOUBLE_039   NUMBER,
      IAU_DOUBLE_040   NUMBER,
      IAU_DOUBLE_041   NUMBER,
      IAU_DOUBLE_042   NUMBER,
      IAU_DOUBLE_043   NUMBER,
      IAU_DOUBLE_044   NUMBER,
      IAU_DOUBLE_045   NUMBER,
      IAU_DOUBLE_046   NUMBER,
      IAU_DOUBLE_047   NUMBER,
      IAU_DOUBLE_048   NUMBER,
      IAU_DOUBLE_049   NUMBER,
      IAU_DOUBLE_050   NUMBER,
      IAU_STRING_001   VARCHAR(2048),
      IAU_STRING_002   VARCHAR(2048),
      IAU_STRING_003   VARCHAR(2048),
      IAU_STRING_004   VARCHAR(2048),
      IAU_STRING_005   VARCHAR(2048),
      IAU_STRING_006   VARCHAR(2048),
      IAU_STRING_007   VARCHAR(2048),
      IAU_STRING_008   VARCHAR(2048),
      IAU_STRING_009   VARCHAR(2048),
      IAU_STRING_010   VARCHAR(2048),
      IAU_STRING_011   VARCHAR(2048),
      IAU_STRING_012   VARCHAR(2048),
      IAU_STRING_013   VARCHAR(2048),
      IAU_STRING_014   VARCHAR(2048),
      IAU_STRING_015   VARCHAR(2048),
      IAU_STRING_016   VARCHAR(2048),
      IAU_STRING_017   VARCHAR(2048),
      IAU_STRING_018   VARCHAR(2048),
      IAU_STRING_019   VARCHAR(2048),
      IAU_STRING_020   VARCHAR(2048),
      IAU_STRING_021   VARCHAR(2048),
      IAU_STRING_022   VARCHAR(2048),
      IAU_STRING_023   VARCHAR(2048),
      IAU_STRING_024   VARCHAR(2048),
      IAU_STRING_025   VARCHAR(2048),
      IAU_STRING_026   VARCHAR(2048),
      IAU_STRING_027   VARCHAR(2048),
      IAU_STRING_028   VARCHAR(2048),
      IAU_STRING_029   VARCHAR(2048),
      IAU_STRING_030   VARCHAR(2048),
      IAU_STRING_031   VARCHAR(2048),
      IAU_STRING_032   VARCHAR(2048),
      IAU_STRING_033   VARCHAR(2048),
      IAU_STRING_034   VARCHAR(2048),
      IAU_STRING_035   VARCHAR(2048),
      IAU_STRING_036   VARCHAR(2048),
      IAU_STRING_037   VARCHAR(2048),
      IAU_STRING_038   VARCHAR(2048),
      IAU_STRING_039   VARCHAR(2048),
      IAU_STRING_040   VARCHAR(2048),
      IAU_STRING_041   VARCHAR(2048),
      IAU_STRING_042   VARCHAR(2048),
      IAU_STRING_043   VARCHAR(2048),
      IAU_STRING_044   VARCHAR(2048),
      IAU_STRING_045   VARCHAR(2048),
      IAU_STRING_046   VARCHAR(2048),
      IAU_STRING_047   VARCHAR(2048),
      IAU_STRING_048   VARCHAR(2048),
      IAU_STRING_049   VARCHAR(2048),
      IAU_STRING_050   VARCHAR(2048),
      IAU_STRING_051   VARCHAR(2048),
      IAU_STRING_052   VARCHAR(2048),
      IAU_STRING_053   VARCHAR(2048),
      IAU_STRING_054   VARCHAR(2048),
      IAU_STRING_055   VARCHAR(2048),
      IAU_STRING_056   VARCHAR(2048),
      IAU_STRING_057   VARCHAR(2048),
      IAU_STRING_058   VARCHAR(2048),
      IAU_STRING_059   VARCHAR(2048),
      IAU_STRING_060   VARCHAR(2048),
      IAU_STRING_061   VARCHAR(2048),
      IAU_STRING_062   VARCHAR(2048),
      IAU_STRING_063   VARCHAR(2048),
      IAU_STRING_064   VARCHAR(2048),
      IAU_STRING_065   VARCHAR(2048),
      IAU_STRING_066   VARCHAR(2048),
      IAU_STRING_067   VARCHAR(2048),
      IAU_STRING_068   VARCHAR(2048),
      IAU_STRING_069   VARCHAR(2048),
      IAU_STRING_070   VARCHAR(2048),
      IAU_STRING_071   VARCHAR(2048),
      IAU_STRING_072   VARCHAR(2048),
      IAU_STRING_073   VARCHAR(2048),
      IAU_STRING_074   VARCHAR(2048),
      IAU_STRING_075   VARCHAR(2048),
      IAU_STRING_076   VARCHAR(2048),
      IAU_STRING_077   VARCHAR(2048),
      IAU_STRING_078   VARCHAR(2048),
      IAU_STRING_079   VARCHAR(2048),
      IAU_STRING_080   VARCHAR(2048),
      IAU_STRING_081   VARCHAR(2048),
      IAU_STRING_082   VARCHAR(2048),
      IAU_STRING_083   VARCHAR(2048),
      IAU_STRING_084   VARCHAR(2048),
      IAU_STRING_085   VARCHAR(2048),
      IAU_STRING_086   VARCHAR(2048),
      IAU_STRING_087   VARCHAR(2048),
      IAU_STRING_088   VARCHAR(2048),
      IAU_STRING_089   VARCHAR(2048),
      IAU_STRING_090   VARCHAR(2048),
      IAU_STRING_091   VARCHAR(2048),
      IAU_STRING_092   VARCHAR(2048),
      IAU_STRING_093   VARCHAR(2048),
      IAU_STRING_094   VARCHAR(2048),
      IAU_STRING_095   VARCHAR(2048),
      IAU_STRING_096   VARCHAR(2048),
      IAU_STRING_097   VARCHAR(2048),
      IAU_STRING_098   VARCHAR(2048),
      IAU_STRING_099   VARCHAR(2048),
      IAU_STRING_100   VARCHAR(2048),
      IAU_DATETIME_001   TIMESTAMP,
      IAU_DATETIME_002   TIMESTAMP,
      IAU_DATETIME_003   TIMESTAMP,
      IAU_DATETIME_004   TIMESTAMP,
      IAU_DATETIME_005   TIMESTAMP,
      IAU_DATETIME_006   TIMESTAMP,
      IAU_DATETIME_007   TIMESTAMP,
      IAU_DATETIME_008   TIMESTAMP,
      IAU_DATETIME_009   TIMESTAMP,
      IAU_DATETIME_010   TIMESTAMP,
      IAU_DATETIME_011   TIMESTAMP,
      IAU_DATETIME_012   TIMESTAMP,
      IAU_DATETIME_013   TIMESTAMP,
      IAU_DATETIME_014   TIMESTAMP,
      IAU_DATETIME_015   TIMESTAMP,
      IAU_DATETIME_016   TIMESTAMP,
      IAU_DATETIME_017   TIMESTAMP,
      IAU_DATETIME_018   TIMESTAMP,
      IAU_DATETIME_019   TIMESTAMP,
      IAU_DATETIME_020   TIMESTAMP,
      IAU_DATETIME_021   TIMESTAMP,
      IAU_DATETIME_022   TIMESTAMP,
      IAU_DATETIME_023   TIMESTAMP,
      IAU_DATETIME_024   TIMESTAMP,
      IAU_DATETIME_025   TIMESTAMP,
      IAU_DATETIME_026   TIMESTAMP,
      IAU_DATETIME_027   TIMESTAMP,
      IAU_DATETIME_028   TIMESTAMP,
      IAU_DATETIME_029   TIMESTAMP,
      IAU_DATETIME_030   TIMESTAMP,
      IAU_DATETIME_031   TIMESTAMP,
      IAU_DATETIME_032   TIMESTAMP,
      IAU_DATETIME_033   TIMESTAMP,
      IAU_DATETIME_034   TIMESTAMP,
      IAU_DATETIME_035   TIMESTAMP,
      IAU_DATETIME_036   TIMESTAMP,
      IAU_DATETIME_037   TIMESTAMP,
      IAU_DATETIME_038   TIMESTAMP,
      IAU_DATETIME_039   TIMESTAMP,
      IAU_DATETIME_040   TIMESTAMP,
      IAU_DATETIME_041   TIMESTAMP,
      IAU_DATETIME_042   TIMESTAMP,
      IAU_DATETIME_043   TIMESTAMP,
      IAU_DATETIME_044   TIMESTAMP,
      IAU_DATETIME_045   TIMESTAMP,
      IAU_DATETIME_046   TIMESTAMP,
      IAU_DATETIME_047   TIMESTAMP,
      IAU_DATETIME_048   TIMESTAMP,
      IAU_DATETIME_049   TIMESTAMP,
      IAU_DATETIME_050   TIMESTAMP,
      IAU_LONGSTRING_001   CLOB,
      IAU_LONGSTRING_002   CLOB,
      IAU_LONGSTRING_003   CLOB,
      IAU_LONGSTRING_004   CLOB,
      IAU_LONGSTRING_005   CLOB,
      IAU_LONGSTRING_006   CLOB,
      IAU_LONGSTRING_007   CLOB,
      IAU_LONGSTRING_008   CLOB,
      IAU_LONGSTRING_009   CLOB,
      IAU_LONGSTRING_010   CLOB,
      IAU_LONGSTRING_011   CLOB,
      IAU_LONGSTRING_012   CLOB,
      IAU_LONGSTRING_013   CLOB,
      IAU_LONGSTRING_014   CLOB,
      IAU_LONGSTRING_015   CLOB,
      IAU_LONGSTRING_016   CLOB,
      IAU_LONGSTRING_017   CLOB,
      IAU_LONGSTRING_018   CLOB,
      IAU_LONGSTRING_019   CLOB,
      IAU_LONGSTRING_020   CLOB,
      IAU_LONGSTRING_021   CLOB,
      IAU_LONGSTRING_022   CLOB,
      IAU_LONGSTRING_023   CLOB,
      IAU_LONGSTRING_024   CLOB,
      IAU_LONGSTRING_025   CLOB,
      IAU_LONGSTRING_026   CLOB,
      IAU_LONGSTRING_027   CLOB,
      IAU_LONGSTRING_028   CLOB,
      IAU_LONGSTRING_029   CLOB,
      IAU_LONGSTRING_030   CLOB,
      IAU_LONGSTRING_031   CLOB,
      IAU_LONGSTRING_032   CLOB,
      IAU_LONGSTRING_033   CLOB,
      IAU_LONGSTRING_034   CLOB,
      IAU_LONGSTRING_035   CLOB,
      IAU_LONGSTRING_036   CLOB,
      IAU_LONGSTRING_037   CLOB,
      IAU_LONGSTRING_038   CLOB,
      IAU_LONGSTRING_039   CLOB,
      IAU_LONGSTRING_040   CLOB,
      IAU_LONGSTRING_041   CLOB,
      IAU_LONGSTRING_042   CLOB,
      IAU_LONGSTRING_043   CLOB,
      IAU_LONGSTRING_044   CLOB,
      IAU_LONGSTRING_045   CLOB,
      IAU_LONGSTRING_046   CLOB,
      IAU_LONGSTRING_047   CLOB,
      IAU_LONGSTRING_048   CLOB,
      IAU_LONGSTRING_049   CLOB,
      IAU_LONGSTRING_050   CLOB,
      IAU_BINARY_001   BLOB,
      IAU_BINARY_002   BLOB,
      IAU_BINARY_003   BLOB,
      IAU_BINARY_004   BLOB,
      IAU_BINARY_005   BLOB,
      IAU_BINARY_006   BLOB,
      IAU_BINARY_007   BLOB,
      IAU_BINARY_008   BLOB,
      IAU_BINARY_009   BLOB,
      IAU_BINARY_010   BLOB,
      IAU_BINARY_011   BLOB,
      IAU_BINARY_012   BLOB,
      IAU_BINARY_013   BLOB,
      IAU_BINARY_014   BLOB,
      IAU_BINARY_015   BLOB,
      IAU_BINARY_016   BLOB,
      IAU_BINARY_017   BLOB,
      IAU_BINARY_018   BLOB,
      IAU_BINARY_019   BLOB,
      IAU_BINARY_020   BLOB,
      IAU_BINARY_021   BLOB,
      IAU_BINARY_022   BLOB,
      IAU_BINARY_023   BLOB,
      IAU_BINARY_024   BLOB,
      IAU_BINARY_025   BLOB,
      IAU_BINARY_026   BLOB,
      IAU_BINARY_027   BLOB,
      IAU_BINARY_028   BLOB,
      IAU_BINARY_029   BLOB,
      IAU_BINARY_030   BLOB,
      IAU_BINARY_031   BLOB,
      IAU_BINARY_032   BLOB,
      IAU_BINARY_033   BLOB,
      IAU_BINARY_034   BLOB,
      IAU_BINARY_035   BLOB,
      IAU_BINARY_036   BLOB,
      IAU_BINARY_037   BLOB,
      IAU_BINARY_038   BLOB,
      IAU_BINARY_039   BLOB,
      IAU_BINARY_040   BLOB,
      IAU_BINARY_041   BLOB,
      IAU_BINARY_042   BLOB,
      IAU_BINARY_043   BLOB,
      IAU_BINARY_044   BLOB,
      IAU_BINARY_045   BLOB,
      IAU_BINARY_046   BLOB,
      IAU_BINARY_047   BLOB,
      IAU_BINARY_048   BLOB,
      IAU_BINARY_049   BLOB,
      IAU_BINARY_050   BLOB
      );

-- PERMISSIONS
GRANT ALL on IAU_CUSTOM_01 to &&1;
GRANT INSERT on IAU_CUSTOM_01 to &&2;
GRANT SELECT on IAU_CUSTOM_01 to &&3;

CREATE TABLE IAU_SCHEMA_VERSION (
 	IAU_VERSION NUMBER,
        IAU_ComponentType VARCHAR(255)
);

GRANT ALL on IAU_SCHEMA_VERSION to &&1;
GRANT SELECT on IAU_SCHEMA_VERSION to &&2;
GRANT SELECT on IAU_SCHEMA_VERSION to &&3;

INSERT INTO IAU_SCHEMA_VERSION VALUES (1.2, 'common');

--Bug 20510165: more privileges

GRANT SELECT on IAU_BASE to &&2;
GRANT SELECT on OIDCOMPONENT to &&2;
GRANT SELECT on WS_POLICYATTACHMENT to &&2;
GRANT SELECT on OWSM_PM_EJB to &&2;
GRANT SELECT on XMLPSERVER to &&2;
GRANT SELECT on SOA_HCFP to &&2;
GRANT SELECT on JPS to &&2;
GRANT SELECT on SOA_B2B to &&2;
GRANT SELECT on OVDCOMPONENT to &&2;
GRANT SELECT on WEBSERVICES to &&2;
GRANT SELECT on STS to &&2;
GRANT SELECT on OWSM_AGENT to &&2;
GRANT SELECT on OHSCOMPONENT to &&2;
GRANT SELECT on OAAM to &&2;
GRANT SELECT on WEBCACHECOMPONENT to &&2;
GRANT SELECT on REPORTSSERVERCOMPONENT to &&2;
GRANT SELECT on DIP to &&2;
GRANT SELECT on ADMINSERVER to &&2;
GRANT SELECT on OIF to &&2;
GRANT SELECT on OAM to &&2; 



-- Create synonyms
CREATE or replace SYNONYM &&2..IAU_CUSTOM_01 FOR &&1..IAU_CUSTOM_01;
CREATE or replace SYNONYM &&3..IAU_CUSTOM_01 FOR &&1..IAU_CUSTOM_01;

CREATE or replace SYNONYM &&2..IAU_SCHEMA_VERSION FOR &&1..IAU_SCHEMA_VERSION;
CREATE or replace SYNONYM &&3..IAU_SCHEMA_VERSION FOR &&1..IAU_SCHEMA_VERSION;

CREATE or replace SYNONYM &&2..IAU_COMMON FOR &&1..IAU_COMMON;
CREATE or replace SYNONYM &&3..IAU_COMMON FOR &&1..IAU_COMMON;

CREATE or replace SYNONYM &&2..IAU_CUSTOM FOR &&1..IAU_CUSTOM;
CREATE or replace SYNONYM &&3..IAU_CUSTOM FOR &&1..IAU_CUSTOM;

CREATE or replace SYNONYM &&2..IAU_USERSESSION FOR &&1..IAU_USERSESSION;
CREATE or replace SYNONYM &&3..IAU_USERSESSION FOR &&1..IAU_USERSESSION;

CREATE or replace SYNONYM &&2..IAU_AUDITSERVICE FOR &&1..IAU_AUDITSERVICE;
CREATE or replace SYNONYM &&3..IAU_AUDITSERVICE FOR &&1..IAU_AUDITSERVICE;

CREATE or replace SYNONYM &&2..ID_SEQ FOR &&1..ID_SEQ;

ALTER SEQUENCE  ID_SEQ CACHE 100 INCREMENT BY 120;

-- indexes
CREATE INDEX AdminServer_Event_Index ON AdminServer(IAU_ID);
CREATE INDEX DIP_Event_Index ON DIP(IAU_ID);
CREATE INDEX JPS_Event_Index ON JPS(IAU_ID);
CREATE INDEX OAM_Event_Index ON OAM(IAU_ID);
CREATE INDEX OAAM_Event_Index ON OAAM(IAU_ID);
CREATE INDEX OHSComponent_Event_Index ON OHSComponent(IAU_ID);
CREATE INDEX OIDComponent_Event_Index ON OIDComponent(IAU_ID);
CREATE INDEX OIF_Event_Index ON OIF(IAU_ID);
CREATE INDEX OVDComponent_Event_Index ON OVDComponent(IAU_ID);
CREATE INDEX OWSM_AGENT_Event_Index ON OWSM_AGENT(IAU_ID);
CREATE INDEX OWSM_PM_EJB_Event_Index ON OWSM_PM_EJB(IAU_ID);
CREATE INDEX ReportsServer_Event_Index ON ReportsServerComponent(IAU_ID);
CREATE INDEX SOA_B2B_Event_Index ON SOA_B2B(IAU_ID);
CREATE INDEX SOA_HCFP_Event_Index ON SOA_HCFP(IAU_ID);
CREATE INDEX STS_Event_Index ON STS(IAU_ID);
CREATE INDEX WebCacheComponent_Event_Index ON WebCacheComponent(IAU_ID);
CREATE INDEX WebServices_Event_Index ON WebServices(IAU_ID);
CREATE INDEX WS_Policy_Event_Index ON WS_PolicyAttachment(IAU_ID);
CREATE INDEX xmlpserver_Event_Index ON xmlpserver(IAU_ID);

CREATE INDEX EVENT_INDEX ON IAU_BASE(IAU_ID);
CREATE INDEX DYN_IAU_RECORD_INDEX ON IAU_COMMON(IAU_ID);
CREATE INDEX DYN_IAU_RECORD_CUSTOM_INDEX ON IAU_CUSTOM(IAU_ID);
CREATE INDEX DYN_IAU_AUDITSERVICE_INDEX ON IAU_AuditService(IAU_ID);
CREATE INDEX DYN_IAU_RECORD_CUSTOM01_INDEX ON IAU_CUSTOM_01(IAU_ID);
CREATE INDEX DYN_IAU_USERSESSION_INDEX ON IAU_USERSESSION(IAU_ID);

CREATE INDEX DYN_USER_INDEX ON IAU_COMMON(IAU_AuditUser);
CREATE INDEX DYN_USER_TENANT_INDEX ON IAU_COMMON(IAU_UserTenantId);
CREATE INDEX DYN_TENANT_INDEX ON IAU_COMMON(IAU_TenantId);
CREATE INDEX DYN_COMPONENT_TYPE_INDEX ON IAU_COMMON(IAU_ComponentType);
CREATE INDEX DYN_EVENT_CATEGORY_INDEX ON IAU_COMMON(IAU_EventCategory);
CREATE INDEX DYN_EVENT_TYPE_INDEX ON IAU_COMMON(IAU_EventType);

COMMIT;
